### PR TITLE
remove unneccesary transation creation

### LINKED ISSUE #1306: fix errors in SecurityIT
tests fail for open services

### PR DESCRIPTION
**Pull request by ssuvorov-fls**
fixes #1306

### CODE REVIEW

File: src/test/java/org/ohdsi/webapi/test/SecurityIT.java [hunk 1]
```diff
@@ -92,18 +82,28 @@ public void testServiceSecurity() throws Exception {
...
 
-                        ResponseEntity<Object> response = this.restTemplate.exchange(uri,
-                                serviceInfo.httpMethod, entity, Object.class);
+                        LOG.info("testing service {}:{}", serviceInfo.httpMethod, uri);
+                        ResponseEntity response;
+                        if (serviceInfo.mediaTypes.contains(MediaType.TEXT_PLAIN_TYPE)) {
+                            response = this.restTemplate.exchange(uri,
+                                    serviceInfo.httpMethod, entity, String.class);
+                        } else {
+                            response = this.restTemplate.exchange(uri,
```
Comment (wivern) [inline src/test/java/org/ohdsi/webapi/test/SecurityIT.java]: Code duplication

Comment (ssuvorov-fls) [reply src/test/java/org/ohdsi/webapi/test/SecurityIT.java]: fixed
