### PR TITLE
Fixes WebAPI logs that grows too fast and includes a lot of noise

### LINKED ISSUE #549: WebAPI logs grow too fast and include a lot of noise

### PR DESCRIPTION
**Pull request by wivern**
Fixes #549

### CODE REVIEW

File: src/main/java/org/ohdsi/webapi/evidence/negativecontrols/NegativeControlTasklet.java [hunk 1]
```diff
@@ -95,7 +95,7 @@ public RepeatStatus execute(final StepContribution contribution, final ChunkCont
                     log.debug("entering tasklet");
 
                     String negativeControlSql = EvidenceService.getNegativeControlSql(task);
-                    log.debug("process negative controls with: \n\t" + negativeControlSql);
+                    log.debug("process negative controls with: \n\t{}", negativeControlSql);
```
Comment (pavgra) [inline src/main/java/org/ohdsi/webapi/evidence/negativecontrols/NegativeControlTasklet.java]: 1. New lines before IDs (here and below) make it harder to read logs
1. Pls make logging consistent - let's start all lines from capital letter

File: src/main/java/org/ohdsi/webapi/service/CohortDefinitionService.java [hunk 2]
```diff
@@ -585,7 +566,7 @@ public void doInTransactionWithoutResult(final TransactionStatus status) {
 
 		final JobParameters jobParameters = builder.toJobParameters();
 
-		log.info(String.format("Beginning cohort cleanup for cohort definition id: \n %s", "" + id));
+		log.info("Beginning cohort cleanup for cohort definition id: \n {}", "" + id);
```
Comment (pavgra) [inline src/main/java/org/ohdsi/webapi/service/CohortDefinitionService.java]: Why newline for single digit? Hard to read

File: src/main/java/org/ohdsi/webapi/service/CohortGenerationService.java [hunk 3]
```diff
@@ -85,7 +85,7 @@ public JobExecutionResource generateCohort(CohortDefinition cohortDefinition, So
 
   public Job buildGenerateCohortJob(CohortDefinition cohortDefinition, Source source, boolean includeFeatures, boolean updateGenerationInfo) {
 
-    log.info(String.format("Beginning generate cohort for cohort definition id: \n %s", "" + cohortDefinition.getId()));
+    log.info("Beginning generate cohort for cohort definition id: \n {}", cohortDefinition.getId());
```
Comment (pavgra) [inline src/main/java/org/ohdsi/webapi/service/CohortGenerationService.java]: Why newline for single digit? Hard to read

File: src/main/java/org/ohdsi/webapi/service/FeatureExtractionService.java [hunk 4]
```diff
@@ -368,7 +368,7 @@ public JobExecutionResource generateFeatures(@PathParam("id") final int id, @Pat
 
 		final JobParameters jobParameters = builder.toJobParameters();
 
-		log.info(String.format("Beginning generate cohort features for cohort definition id: \n %s", "" + id));
+		log.info("Beginning generate cohort features for cohort definition id: \n {}", id);
```
Comment (pavgra) [inline src/main/java/org/ohdsi/webapi/service/FeatureExtractionService.java]: Why newline for single digit? Hard to read
