### PR TITLE
Fixes Cancel Cohort generation button doesn't kill underlying DB query

### LINKED ISSUE #579: Cancel Cohort generation button doesn't kill underlying DB query
### Steps to reproduce:
1. Start cohort generation
2. Press Cancel button
3. Execute (in case of PG):
```
SELECT pid, age(clock_timestamp(), query_start), usename, query 
FROM pg_stat_activity 
WHERE query != '<IDLE>' AND query NOT ILIKE '%pg_stat_activity%' 
ORDER BY query_start desc;
```

### Expected results
Cohort generation query is *not* presented in the results.

### Actual results
The query is presented in the results and still running.

### PR DESCRIPTION
**Pull request by wivern**
fixes #579

### CODE REVIEW

File: src/main/java/org/ohdsi/webapi/util/CancelableJdbcTemplate.java [hunk 1]
```diff
@@ -0,0 +1,91 @@
...
+      private String currSql;
+
+      @Override
+      public int[] doInStatement(Statement stmt) throws SQLException, DataAccessException {
+        int[] rowsAffected = new int[sql.length];
+        cancelOp.setStatement(stmt);
+        if (JdbcUtils.supportsBatchUpdates(stmt.getConnection())) {
+          for (String sqlStmt : sql) {
+            this.currSql = appendSql(this.currSql, sqlStmt);
+            stmt.addBatch(sqlStmt);
```
Comment (pavgra) [inline src/main/java/org/ohdsi/webapi/util/CancelableJdbcTemplate.java]: Why is `stmt.addBatch` inside the loop? Shouldn't it be outside?

File: src/main/java/org/ohdsi/webapi/service/CohortDefinitionService.java [hunk 2]
```diff
@@ -497,9 +505,25 @@ public Response cancelGenerateCohort(@PathParam("id") final int id, @PathParam("
     });
 
     cohortGenerationService.getJobExecution(source, id)
-            .ifPresent(job -> {
+            .ifPresent(jobExecution -> {
               try {
-                jobOperator.stop(job.getJobId());
+                Job job = cohortGenerationService.getRunningJob(jobExecution.getJobId());
```
Comment (pavgra) [inline src/main/java/org/ohdsi/webapi/service/CohortDefinitionService.java]: Shouldn't this logic be moved into a shared utils so that it can be applied in other places?

File: src/main/java/org/ohdsi/webapi/cohortdefinition/GenerateCohortTasklet.java [hunk 3]
```diff
@@ -178,6 +171,10 @@ public RepeatStatus execute(final StepContribution contribution, final ChunkCont
 
   @Override
   public void stop() {
+    try {
```
Comment (pavgra) [inline src/main/java/org/ohdsi/webapi/cohortdefinition/GenerateCohortTasklet.java]: Shouldn't this method be moved into generic tasklet?

File: src/main/java/org/ohdsi/webapi/util/CancelableJdbcTemplate.java [hunk 4]
```diff
@@ -0,0 +1,91 @@
...
+import org.springframework.jdbc.support.JdbcUtils;
+import org.springframework.util.Assert;
+import org.springframework.util.StringUtils;
+
+import javax.sql.DataSource;
+import java.sql.BatchUpdateException;
+import java.sql.SQLException;
+import java.sql.Statement;
+
+public class CancelableJdbcTemplate extends JdbcTemplate {
```
Comment (pavgra) [inline src/main/java/org/ohdsi/webapi/util/CancelableJdbcTemplate.java]: Why this tasklet is not applied to IR / CC?

File: src/main/java/org/ohdsi/webapi/util/CancelableJdbcTemplate.java (hunk 1 above)
Comment (wivern) [reply src/main/java/org/ohdsi/webapi/util/CancelableJdbcTemplate.java]: Generally sql is an array of statetement, but `Statement.addBatch` accepts single statement to batch execution. 
This can be replaced with join for `this.currSql` and `Arrays.forEach` for addBatch but in this case we have two loops instead one.
The code above just borrowed from Spring JdbcTemplate as is.

File: src/main/java/org/ohdsi/webapi/cohortdefinition/GenerateCohortTasklet.java (hunk 3 above)
Comment (wivern) [reply src/main/java/org/ohdsi/webapi/cohortdefinition/GenerateCohortTasklet.java]: Hmmm, give me a time to think about that...

**Comment by chrisknoll** [comment]
I think we need a merge from master here so we can ensure all the latest code is accounted for.

**Comment by pavgra** [comment]
@wivern , would be very useful if canceled generation displays "Canceled" status

image

**Comment by pavgra** [comment]
@wivern , would be good to display "Canceled" status for interrupted generations instead of "Failed". Otherwise, tested for Cohorts, CC, IRs and Pathways and looks good.

**Comment by pavgra** [comment]
@wivern , would be good to show same results for both persons and records columns for canceled jobs. I would suggest using "..." in both cases

image
