### PR TITLE
Fixes Non-optimal evaluation of priority daimons

### LINKED ISSUE #1429: Non-optimal evaluation of priority daimons
1. `SourceController.getPriorityDaimons` iterates over all source diamons and for each of them executes `getPrioritySourceForDaimon`
2. The `getPrioritySourceForDaimon` relies on `sourceAccessor.hasAccess(source)`
3. Therefore, for a single source, we can do the same security check 6 times (number of diamons) which is redundant. 
**However, the biggest problem** takes place when some Shiro Realm points e.g. to Active Directory that is offline. Then, the realm would wait until the connection attempt reaches timeout and the security check would take ~20sec for the offline Active Directory. But, due to the repetition of the check, the total execution time would be 20sec * 6=120 sec = 2 min instead of just 20 sec.

### PR DESCRIPTION
**Pull request by wivern**
Fixes #1429

### CODE REVIEW

File: src/main/java/org/ohdsi/webapi/source/SourceService.java [hunk 1]
```diff
@@ -126,6 +122,22 @@ public Source getPrioritySourceForDaimon(SourceDaimon.DaimonType daimonType) {
...
 
+    public Map<SourceDaimon.DaimonType, Source> getPriorityDaimons() {
+
+        Map<Integer, Boolean> checkedSources = new HashMap<>();
+        Map<SourceDaimon.DaimonType, Source> priorityDaimons = new HashMap<>();
+        Arrays.asList(SourceDaimon.DaimonType.values()).forEach(d -> {
+
+            List<Source> sources = sourceRepository.findAllSortedByDiamonPrioirty(d);
+            Optional<Source> source = sources.stream().filter(s -> checkedSources.computeIfAbsent(s.getSourceId(),
+                    v -> sourceAccessor.hasAccess(s)
```
Comment (YaroslavTir) [inline src/main/java/org/ohdsi/webapi/source/SourceService.java]: this part is not clear. I personally don't like it when in filter happens something besides checking. I understand that is it is webapi approach, but can you extract the check to separate method, with an understandable name.
exp: 
```
    public Map<SourceDaimon.DaimonType, Source> getPriorityDaimons() {

        Map<Integer, Boolean> checkedSources = new HashMap<>();
        Map<SourceDaimon.DaimonType, Source> priorityDaimons = new HashMap<>();

        Arrays.asList(SourceDaimon.DaimonType.values()).forEach(d -> {

            Optional<Source> source = sourceRepository.findAllSortedByDiamonPrioirty(d).stream()
                    .filter(s -> isSourceAvailable(s, checkedSources, connectionAvailability))
                    .findFirst();

            source.ifPresent(s -> priorityDaimons.put(d, s));
        });
        return priorityDaimons;
    }

    private Boolean isSourceAvailable(Source s, Map<Integer, Boolean> sourceCheckedCache, Map<Source, Boolean> connectionAvailabilityCache) {
        return sourceCheckedCache.computeIfAbsent(
                s.getSourceId(),
                v -> sourceAccessor.hasAccess(s) && connectionAvailabilityCache.computeIfAbsent(s, this::checkConnectionSafe));
    }
```

File: src/main/java/org/ohdsi/webapi/source/SourceService.java [hunk 2]
```diff
@@ -126,6 +122,22 @@ public Source getPrioritySourceForDaimon(SourceDaimon.DaimonType daimonType) {
...
+                            && connectionAvailability.computeIfAbsent(s, this::checkConnectionSafe)))
+                    .findFirst();
+            source.map(s -> priorityDaimons.put(d, s));
```
Comment (YaroslavTir) [inline src/main/java/org/ohdsi/webapi/source/SourceService.java]: I guess ifPresent fits better here.
