### PR TITLE
Ensure unique feature analysis names upon import - fixes #1192

### LINKED ISSUE #1192: Characterization import fails with custom features specified
Using this design: [cc-import-fails-with-custom-feature.txt](https://github.com/OHDSI/WebAPI/files/3267366/cc-import-fails-with-custom-feature.txt), attempt to import this design into an Atlas instance more than one time.

The second attempt will fail with the following error: 

> "Violation of UNIQUE KEY constraint 'uq_fe_name'. Cannot insert duplicate key in object 'dbo.fe_analysis'. The duplicate key value is (Age>18 & Gender=Male).",

Related to #1100

### PR DESCRIPTION
**Pull request by anthonysena**
Adds checks to ensure feature analysis names are not duplicated upon import of a cohort characterization design. This fixes issue #1192. I've tested this against SQL Server and PostgreSQL.

### CODE REVIEW

File: src/main/java/org/ohdsi/webapi/cohortcharacterization/CcServiceImpl.java [hunk 1]
```diff
@@ -631,12 +631,14 @@ private void importAnalyses(final CohortCharacterizationEntity entity, final Coh
             switch (analysis.getType()) {
                 case CRITERIA_SET:
                     FeAnalysisWithCriteriaEntity criteriaAnalysis = (FeAnalysisWithCriteriaEntity)analysis;
+                    criteriaAnalysis.setName(NameUtils.getNameWithSuffix(criteriaAnalysis.getName(), this::getFeNamesLike));
```
Comment (pavgra) [inline src/main/java/org/ohdsi/webapi/cohortcharacterization/CcServiceImpl.java]: I would add here the same logic as we have for Cohorts: first, check if such analysis already exists (search for analysis with the "design" field having the same value as imported analysis) and only then, if such analysis doesn't exist, create it. Otherwise, if analysis exists, do not duplicate entities

Comment (anthonysena) [reply src/main/java/org/ohdsi/webapi/cohortcharacterization/CcServiceImpl.java]: @pavgra - I've pushed up a commit https://github.com/OHDSI/WebAPI/pull/1196/commits/c9160cb200313a9ad78c1f6da9f1b61eaddfa426 which will address the CUSTOM_FE duplication. 

As discussed offline, handling the CRITERIA_SET type is a bit more complex since this data structure represents 1 or more entries in the `fe_analysis_criteria`. If someone from your team can look at this case and provide a solution, I'd be happy to review & test.

Comment (AntonStepanof) [reply src/main/java/org/ohdsi/webapi/cohortcharacterization/CcServiceImpl.java]: added logic for CRITERIA_SET

File: src/main/java/org/ohdsi/webapi/cohortcharacterization/CcServiceImpl.java [hunk 2]
```diff
@@ -701,5 +724,13 @@ private void invalidateGenerations() {
             return null;
         });
     }
+    
+    private List<String> getFeNamesLike(String name) {
+        return analysisService.getNamesLike(name);
+    }
+    
+    private Optional<FeAnalysisEntity> getFeByDesignAndName(final FeAnalysisWithStringEntity withStringEntity, final String feAnalysisName) {
```
Comment (pavgra) [inline src/main/java/org/ohdsi/webapi/cohortcharacterization/CcServiceImpl.java]: What is the reason for the function? - why don't you reference `analysisService.findByDesignAndName` directly?

File: src/main/java/org/ohdsi/webapi/cohortcharacterization/CcImportEvent.java [hunk 3]
```diff
@@ -1,18 +1,16 @@
 package org.ohdsi.webapi.cohortcharacterization;
 
-import org.ohdsi.webapi.cohortcharacterization.domain.CohortCharacterizationEntity;
+import java.util.List;
 
 public class CcImportEvent {
 
-    private CohortCharacterizationEntity entity;
+    private List<Integer> savedAnalysesIds;
```
Comment (pavgra) [inline src/main/java/org/ohdsi/webapi/cohortcharacterization/CcImportEvent.java]: Why?

File: src/main/java/org/ohdsi/webapi/cohortcharacterization/CcServiceImpl.java [hunk 4]
```diff
@@ -622,29 +624,50 @@ private void gatherForDistribution(final CcDistributionStat stat, final ResultSe
...
 
         for (final FeAnalysisEntity analysis : entity.getFeatureAnalyses()) {
             switch (analysis.getType()) {
                 case CRITERIA_SET:
-                    FeAnalysisWithCriteriaEntity criteriaAnalysis = (FeAnalysisWithCriteriaEntity)analysis;
-                    entityAnalyses.add(analysisService.createCriteriaAnalysis(criteriaAnalysis));
+                    FeAnalysisWithCriteriaEntity<? extends FeAnalysisCriteriaEntity> criteriaAnalysis = (FeAnalysisWithCriteriaEntity) analysis;
+                    List<? extends FeAnalysisCriteriaEntity> design = criteriaAnalysis.getDesign();
+                    Optional<FeAnalysisEntity> entityCriteriaSet = analysisService
+                            .findByCriteriaListAndName(design, criteriaAnalysis.getName());
```
Comment (pavgra) [inline src/main/java/org/ohdsi/webapi/cohortcharacterization/CcServiceImpl.java]: Why do you include the name into the search? We do not do that for cohorts import

File: src/main/java/org/ohdsi/webapi/cohortcharacterization/CcServiceImpl.java (hunk 2 above)
Comment (AntonStepanof) [reply src/main/java/org/ohdsi/webapi/cohortcharacterization/CcServiceImpl.java]: fixed

File: src/main/java/org/ohdsi/webapi/cohortcharacterization/CcImportEvent.java (hunk 3 above)
Comment (AntonStepanof) [reply src/main/java/org/ohdsi/webapi/cohortcharacterization/CcImportEvent.java]: I keep list of saved ids for prevent this error: Can't create permission - it already exists
For case when analysis already present in db.

File: src/main/java/org/ohdsi/webapi/cohortcharacterization/CcServiceImpl.java (hunk 4 above)
Comment (AntonStepanof) [reply src/main/java/org/ohdsi/webapi/cohortcharacterization/CcServiceImpl.java]: updated

File: src/main/java/org/ohdsi/webapi/feanalysis/FeAnalysisServiceImpl.java [hunk 5]
```diff
@@ -174,6 +176,41 @@ public void deleteAnalysis(FeAnalysisEntity entity) {
...
+        List<String> currentList = curCriteriaList.stream().map(FeAnalysisCriteriaEntity::getExpressionString).collect(Collectors.toList());
+        List<String> newList = newCriteriaList.stream().map(FeAnalysisCriteriaEntity::getExpressionString).collect(Collectors.toList());
+        return CollectionUtils.isEqualCollection(currentList, newList);
+    }
+
+    private Optional<FeAnalysisEntity> findByDesignAndPredicate(final String design, final Predicate<FeAnalysisEntity> f) {
+        List<FeAnalysisEntity> detailsFromDb = analysisRepository.findByDesign(design);
+        return detailsFromDb
+                .stream()
+                .filter(v -> Objects.equals(v.getDesign(), design))
```
Comment (pavgra) [inline src/main/java/org/ohdsi/webapi/feanalysis/FeAnalysisServiceImpl.java]: In what case this expression won't return `true`?

File: src/main/java/org/ohdsi/webapi/cohortcharacterization/CcImportEvent.java (hunk 3 above)
Comment (pavgra) [reply src/main/java/org/ohdsi/webapi/cohortcharacterization/CcImportEvent.java]: Could you put this comment into the code, please?

Comment (AntonStepanof) [reply src/main/java/org/ohdsi/webapi/cohortcharacterization/CcImportEvent.java]: added comment

File: src/main/java/org/ohdsi/webapi/feanalysis/FeAnalysisServiceImpl.java (hunk 5 above)
Comment (AntonStepanof) [reply src/main/java/org/ohdsi/webapi/feanalysis/FeAnalysisServiceImpl.java]: yes, I removed this filter

File: src/main/java/org/ohdsi/webapi/cohortcharacterization/CcImportEvent.java (hunk 3 above)
Comment (AntonStepanof) [reply src/main/java/org/ohdsi/webapi/cohortcharacterization/CcImportEvent.java]: added comment

File: src/main/java/org/ohdsi/webapi/cohortcharacterization/CcServiceImpl.java [hunk 6]
```diff
@@ -622,29 +624,49 @@ private void gatherForDistribution(final CcDistributionStat stat, final ResultSe
...
+                    }
                     break;
                 case PRESET:
                     entityAnalyses.add(presetAnalysesMap.get(analysis.getDesign()));
                     break;
                 case CUSTOM_FE:
-                    entityAnalyses.add(analysisService.createAnalysis(analysis));
+                    FeAnalysisWithStringEntity withStringEntity = (FeAnalysisWithStringEntity) analysis;
+                    Optional<FeAnalysisEntity> findAnalysisResult = analysisService.findByDesignAndName(withStringEntity, withStringEntity.getName());
+                    if (findAnalysisResult.isPresent()) {
```
Comment (pavgra) [inline src/main/java/org/ohdsi/webapi/cohortcharacterization/CcServiceImpl.java]: This `if` statement is very similar to the one in CRITERIA_SET case. Cannot we create a templated function for this?

Comment (AntonStepanof) [reply src/main/java/org/ohdsi/webapi/cohortcharacterization/CcServiceImpl.java]: updated

Comment (AntonStepanof) [reply src/main/java/org/ohdsi/webapi/cohortcharacterization/CcServiceImpl.java]: updated
