### PR TITLE
Fixed Cohort Characterization with Strata fails with temp table already exists

### LINKED ISSUE #731: Cohort Characterization with Strata fails with temp table already exists
When performing a cohort characterization with stratification, an error results when executing on PDW (assuming this error is not db specific):

```
java.lang.RuntimeException: java.util.concurrent.ExecutionException: org.springframework.jdbc.UncategorizedSQLException: ConnectionCallback; uncategorized SQLException for SQL [IF XACT_STATE() = 1 COMMIT; CREATE TABLE  #qualified_events
  WITH (LOCATION = USER_DB, DISTRIBUTION = HASH(person_id)) AS
SELECT
ROW_NUMBER() OVER (partition by E.subject_id order by E.cohort_start_date) AS event_id, E.subject_id AS  person_id, E.cohort_start_date AS start_date, E.cohort_end_date AS end_date, OP.observation_period_start_date AS op_start_date, OP.observation_period_end_date AS op_end_date

FROM
cknoll1.cohort_hp1j544n E
      JOIN dbo.observation_period OP ON E.subject_id = OP.person_id AND E.cohort_start_date >= OP.observation_period_start_date AND E.cohort_start_date <= OP.observation_period_end_date
    WHERE cohort_definition_id = ?;

INSERT INTO #strata_cohort_1(cohort_definition_id, strata_id, subject_id, cohort_start_date, cohort_end_date)
SELECT ? AS cohort_definition_id, ? AS strata_id, q.person_id as subject_id, q.start_date AS cohort_start_date, q.end_date AS cohort_end_date
  FROM #qualified_events q
  JOIN (SELECT person_id FROM (
select 0 as index_id, person_id, event_id
FROM
(
  select E.person_id, E.event_id 
  FROM #qualified_events E
  INNER JOIN
  (
    
SELECT 0 as index_id, p.person_id, p.event_id
FROM #qualified_events P
INNER JOIN
(
  
SELECT C.person_id, C.condition_occurrence_id as event_id, C.condition_start_date as start_date, COALESCE(C.condition_end_date, DATEADD(day,1,C.condition_start_date)) as end_date, C.CONDITION_CONCEPT_ID as TARGET_CONCEPT_ID, C.visit_occurrence_id
FROM 
(
  SELECT co.* 
  FROM dbo.CONDITION_OCCURRENCE co
  JOIN #Codesets codesets on ((co.condition_concept_id = codesets.concept_id and codesets.codeset_id = 0))
) C




) A on A.person_id = P.person_id and A.START_DATE >= P.OP_START_DATE AND A.START_DATE <= P.OP_END_DATE AND A.START_DATE >= P.OP_START_DATE AND A.START_DATE <= DATEADD(day,-1,P.START_DATE)
GROUP BY p.person_id, p.event_id
HAVING COUNT(A.TARGET_CONCEPT_ID) >= 1


  ) CQ on E.person_id = CQ.person_id and E.event_id = CQ.event_id
  GROUP BY E.person_id, E.event_id
  HAVING COUNT(index_id) = 1
) G

) st GROUP BY person_id) sti ON sti.person_id = q.person_id
;

IF XACT_STATE() = 1 COMMIT; IF OBJECT_ID('#qualified_events', 'U') IS NOT NULL  DROP TABLE  #qualified_events;]; SQL state [S0001]; error code [2714]; There is already an object named '#qualified_events' in the database.;
```

Steps to reproduce:
Create new cohort characterization
Add strata to the analysis. I created a strata defined as: 'having at least 1 condition occurrence of Psoriasis'
Execute Analysis
Error should appear in log, and the execution will report failed.

### PR DESCRIPTION
**Pull request by wivern**
fixes #731

### CODE REVIEW

**Comment by wivern** [comment]
This issue was not tested on PDW but on Impala

**Comment by chrisknoll** [comment]
Would you mind explaining the usage of: `<jdbc.suppressInvalidApiException>true</jdbc.suppressInvalidApiException>`?

File: src/main/resources/resources/cohortcharacterizations/sql/createCohortTable.sql [hunk 1]
```diff
@@ -1,3 +1,5 @@
+IF OBJECT_ID('@temp_database_schema.@target_table', 'U') IS NOT NULL DROP TABLE @temp_database_schema.@target_table;
```
Comment (chrisknoll) [inline src/main/resources/resources/cohortcharacterizations/sql/createCohortTable.sql]: I would like for us to avoid this ``IF OBJECT_ID() test`` for dropping the table.  Reason is this:

What if the table did already exist? Wouldn't dropping a table that some other thread may have created be a problem?  If you do not expect that table to exist, wouldn't it be better to get the exception when trying to create the same table twice, instead of hiding the potential logical / threadding problem behind an `If OBJECT_ID()` check?

**Comment by chrisknoll** [comment]
Since I completed some PRs, I have merged master into this PR to ensure that we're working with the latest master's changes.

Unfortunately, i am still seeing the error with the table already existing:
`
Caused by: java.util.concurrent.ExecutionException: org.springframework.jdbc.UncategorizedSQLException: ConnectionCallback; uncategorized SQLException for SQL []; SQL state [S0001]; error code [2714]; There is already an object named '#qualified_events' in the database.; nested exception is com.microsoft.sqlserver.jdbc.SQLServerException: There is already an object named '#qualified_events' in the database.
`
