### PR TITLE
Move call to proxy outside (#1364)

### LINKED ISSUE #1364: impossible to create a copy of PLP
1) Try to copy any plp(prediction)

expected:The copy has been created

actual:
front:
image

 back:
WebAPI/prediction/{id}/copyRequest Method: GETStatus Code: 500{"payload":{"cause":null,"stackTrace":[],"message":"An exception ocurred: org.springframework.core.convert.ConversionFailedException","localizedMessage":"An exception ocurred: org.springframework.core.convert.ConversionFailedException","suppressed":[]},"headers":{"id":"249a112a-4afe-32c3-1543-b30a203dac25","timestamp":1573718841739}}

as a result - the copy has been created, but it's unable for editing

### PR DESCRIPTION
**Pull request by ssuvorov-fls**
fixes #1364

### CODE REVIEW

File: src/main/java/org/ohdsi/webapi/prediction/PredictionServiceImpl.java [hunk 1]
```diff
@@ -135,6 +144,9 @@ public PredictionAnalysis createAnalysis(PredictionAnalysis pred) {
         Date currentTime = Calendar.getInstance().getTime();
         pred.setCreatedBy(getCurrentUser());
         pred.setCreatedDate(currentTime);
+        // Fields with information about modifications have to be reseted
+        pred.setModifiedBy(null);
+        pred.setModifiedDate(null);
```
Comment (wivern) [inline src/main/java/org/ohdsi/webapi/prediction/PredictionServiceImpl.java]: Why not to add the same for other analyses types (Estimation, Pathways etc.)?

Comment (ssuvorov-fls) [reply src/main/java/org/ohdsi/webapi/prediction/PredictionServiceImpl.java]: done
