### PR TITLE
Fixes failed Cohort Pathways on Impala

### LINKED ISSUE #1271: Cohort Pathways fails on Impala
Odysseus instance, analysis 143
Error:
```
org.ohdsi.webapi.exception.AtlasException: java.lang.RuntimeException: java.util.concurrent.ExecutionException: org.springframework.jdbc.UncategorizedSQLException: StatementCallback; uncategorized SQLException for SQL [update synpuf_53_test_results.i1f0t2a2collapsed_dates_events set cohort_end_date = DATE_ADD(CASE TYPEOF(cohort_end_date ) WHEN 'TIMESTAMP' THEN CAST(cohort_end_date  AS TIMESTAMP) ELSE TO_UTC_TIMESTAMP(CONCAT_WS('-', SUBSTR(CAST(cohort_end_date  AS STRING), 1, 4), SUBSTR(CAST(cohort_end_date  AS STRING), 5, 2), SUBSTR(CAST(cohort_end_date  AS STRING), 7, 2)), 'UTC') END, 1) where cohort_start_date = cohort_end_date]; SQL state [HY000]; error code [500051]; [Simba][ImpalaJDBCDriver](500051) ERROR processing query/statement. Error Code: 0, SQL state: TStatus(statusCode:ERROR_STATUS, sqlState:HY000, errorMessage:AnalysisException: Impala does not support modifying a non-Kudu table: synpuf_53_test_results.i1f0t2a2collapsed_dates_events
), Query: update synpuf_53_test_results.i1f0t2a2collapsed_dates_events set cohort_end_date = DATE_ADD(CASE TYPEOF(cohort_end_date ) WHEN 'TIMESTAMP' THEN CAST(cohort_end_date  AS TIMESTAMP) ELSE TO_UTC_TIMESTAMP(CONCAT_WS('-', SUBSTR(CAST(cohort_end_date  AS STRING), 1, 4), SUBSTR(CAST(cohort_end_date  AS STRING), 5, 2), SUBSTR(CAST(cohort_end_date  AS STRING), 7, 2)), 'UTC') END, 1) where cohort_start_date = cohort_end_date.; nested exception is java.sql.SQLException: [Simba][ImpalaJDBCDriver](500051) ERROR processing query/statement. Error Code: 0, SQL state: TStatus(statusCode:ERROR_STATUS, sqlState:HY000, errorMessage:AnalysisException: Impala does not support modifying a non-Kudu table: synpuf_53_test_results.i1f0t2a2collapsed_dates_events
), Query: update synpuf_53_test_results.i1f0t2a2collapsed_dates_events set cohort_end_date = DATE_ADD(CASE TYPEOF(cohort_end_date ) WHEN 'TIMESTAMP' THEN CAST(cohort_end_date  AS TIMESTAMP) ELSE TO_UTC_TIMESTAMP(CONCAT_WS('-', SUBSTR(CAST(cohort_end_date  AS STRING), 1, 4), SUBSTR(CAST(cohort_end_date  AS STRING), 5, 2), SUBSTR(CAST(cohort_end_date  AS STRING), 7, 2)), 'UTC') END, 1) where cohort_start_date = cohort_end_date.
	at org.ohdsi.webapi.common.generation.TransactionalTasklet.execute(TransactionalTasklet.java:42)
	at org.springframework.batch.core.step.tasklet.TaskletStep$ChunkTransactionCallback.doInTransaction(TaskletStep.java:406)
	at org.springframework.batch.core.step.tasklet.TaskletStep$ChunkTransactionCallback.doInTransaction(TaskletStep.java:330)
	at org.sp
```

### PR DESCRIPTION
**Pull request by wivern**
Fixes #1271

### CODE REVIEW

File: src/main/resources/resources/pathway/runPathwayAnalysis.sql [hunk 1]
```diff
@@ -159,9 +167,9 @@ WHERE 1 = 1 {@max_depth != ''}?{ AND ordinal <= @max_depth };
 INSERT INTO @target_database_schema.pathway_analysis_stats (pathway_analysis_generation_id, target_cohort_id, target_cohort_count, pathways_count)
 SELECT
   @generation_id as pathway_analysis_generation_id,
-  @pathway_target_cohort_id as target_cohort_id,
-  target_count.cnt AS target_cohort_count,
-  pathway_count.cnt AS pathways_count
+  CAST(@pathway_target_cohort_id AS INT) AS target_cohort_id,
+  CAST(target_count.cnt AS INT) AS target_cohort_count,
```
Comment (chrisknoll) [inline src/main/resources/resources/pathway/runPathwayAnalysis.sql]: counts should be BIGINT because they could exceed the INT datatype max.  We should confirm that pathway_analysis_stats defines the count columns as BIGINT (I believe they do).

**Comment by pavgra** [comment]
@chrisknoll , are you OK with the latest changes?
