### PR TITLE
Fixed Oracle migrations.

### LINKED ISSUE #1680: Oracle migrations failed
Application fails to start on Oracle DB (tested on 19c). Problem migrations:

V2.7.8.20200728164800__add_conceptset_permission.sql
V2.8.0.20200109100200__cohort_sample_tables.sql
V2.8.0.20200122173000__insert_cohort_sample_permissions.sql
V2.8.0.20201022120031__concept_ancestor_and_descendants.sql

### PR DESCRIPTION
**Pull request by chrisknoll**
Altered CohortSample.java size column to be quoted for Oracle compatibility.

Fixes #1680.

### CODE REVIEW

File: src/main/java/org/ohdsi/webapi/cohortsample/CohortSample.java [hunk 1]
```diff
@@ -51,7 +51,7 @@
 	@Column(name = "gender_concept_ids")
 	private String genderConceptIds;
 
-	@Column
+	@Column(name = "\"size\"")
```
Comment (anthonysena) [inline src/main/java/org/ohdsi/webapi/cohortsample/CohortSample.java:54]: Verified this works on PG

**Review by anthonysena — APPROVED** [review]
